### PR TITLE
Added forum category filtering with categories from database

### LINKED ISSUE #194: Forum Categories

### PR DESCRIPTION
**Pull request by ethanbwaite**
closes #194

### CODE REVIEW

**Comment by Andrii-I** [comment]
nit: 
Somewhere in the future, we might want to add some kind of forum post category selector like drop-down menu or typing keywords into "search"

**Comment by ethanbwaite** [comment]
> nit:
> Somewhere in the future, we might want to add some kind of forum post category selector like drop-down menu or typing keywords into "search"

yeah this is a good idea, the next feature related to categories is linking search results for disorders to the forum but also a list next to the forum of all the categories would be good

**Comment by ethanbwaite** [comment]
> nit:
> Somewhere in the future, we might want to add some kind of forum post category selector like drop-down menu or typing keywords into "search"

yeah this is a good idea, the next feature related to categories is linking search results for disorders to the forum but also a list next to the forum of all the categories would be good

**Comment by allenzhai** [comment]
LGTM

**Pull request merged**
