### PR TITLE
Issue166 LoginModal styling; RegistrationModal styling and verified status selector (old name: Issue166 added LoginModal styling (RegistrationModal styling to be added with separate PR))

### PR DESCRIPTION
**Pull request by Andrii-I**

### CODE REVIEW

**Comment by Andrii-I** [comment]
One review should be enough

**Comment by allenzhai** [comment]
LGTM

**Comment by ethanbwaite** [comment]
was this the PR that was merged earlier?

**Comment by Andrii-I** [comment]
@ethanbwaite removed !important from this code, closed insignificant "micro" PR #197

**Comment by Andrii-I** [comment]
Taking in account the fact that submission was not yet fully approved/merge, in order to avoid merge conflicts it seems a better option to add RegistrationModal code to the current PR vs creating new PR

**Pull request merged**
